### ISSUE TITLE
colorWheelShader

### ISSUE THREAD

**Issue by plutovman** [CooperCorona/VoronoiVisualizer#3]
Hello,

I tried to run your code, but got the following errors about missing files

NoiseGenerator/NoiseGenerator/ColorWheelShader.fsh: No such file or directory
NoiseGenerator/NoiseGenerator/ColorWheelShader.vsh: No such file or directory

I hope you don't mind my reaching out.  I have always wanted to learn about voronoi diagrams, and would be very interested in seeing your opengl/swift implementation.

**Comment by CooperCorona** [comment]
Whoops, I linked some files incorrectly. They should be fixed now.
Don't forget you'll need to clone [CoronaConvenience](https://github.com/CooperCorona/CoronaConvenience), [CoronaStructures](https://github.com/CooperCorona/CoronaStructures), [CoronaGL](https://github.com/CooperCorona/CoronaGL), and [Voronoi](https://github.com/CooperCorona/Voronoi) as dependencies.

**Comment by plutovman** [comment]
thank you.  will try again later tonight.  may i ask, are you doing this as part of a research effort? are you in a grad program?  I ask, because I don't see a lot of activity in this domain that is not game-related, especially with swift and OpenGL.  I'm just curious and hope you don't mind the query.

Thanks

**Comment by CooperCorona** [comment]
I am not in a grad program; I originally wrote the Voronoi library to perform shattering effects in games.  I wrote VoronoiVisualizer because I like having the ability to export images of Voronoi diagrams. I think it helps solidify the concept to see the points and the diagrams they create.

**Comment by plutovman** [comment]
That's great work.  I'm looking forward to diving into your code to see how you've put it all together.  May I ask how long it took you to organize and implement?  From what I can see, the design and flexibility of the library is very mature and well thought out.  Thank you for making this available to study.

**Comment by CooperCorona** [comment]
The Voronoi library itself was several months of wrestling with Fortune's Algorithm on-and-off, with a  couple months dedicated to fixing edge cases. VoronoiVisualizer took a month or two since it derives most of its functionality from Voronoi.
